server.port: 7002

logging:
  level:
    root: INFO
    org.rainzha: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
---
spring.profiles: docker

spring.data.mongodb:
  host: mongodb
  port: 27017
  database: recommendation-db

server.port: 8080