server.port: 7001

logging:
  level:
    root: INFO
    org.rainzha.microservices: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
---
spring.profiles: docker

spring.data.mongodb:
  host: mongodb
  port: 27017
  database: product-db

server.port: 8080
