apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-rainhandson
  labels:
    svc: product
    app: rainhandson
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: product
      app: rainhandson
  template:
    metadata:
      labels:
        svc: product
        app: rainhandson
    spec:
      containers:
        - name: product-rainhandson
          image: registry.cn-hangzhou.aliyuncs.com/rainzha/product-service:1.0
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: product-rainhandson
spec:
  ports:
    - port: 8080
  selector:
    svc: product
    app: rainhandson